$schema: "https://json-schema.org/draft/2020-12/schema"
description: main configuration schema for the workflow
properties:
  samplesheet:
    type: string
    description: path to sample-sheet TSV file

  conda:
    type: object
    properties:
      cutadapt:
        type: string
        description: path to cutadapt conda env or yaml specification file
      mixcr:
        type: string
        description: path to mixcr conda env or yaml specification file
      plot:
        type: string
        description: path to plot conda env or yaml specification file
  
  threads:
    type: object
    properties:
      cutadapt:
        type: number
        description: number of threads to use for cutadapt
      align:
        type: number
        description: number of threads to use for mixcr align
      extend:
        type: number
        description: number of threads to use for mixcr extend
      assemble_contigs:
        type: number
        description: number of threads to use for mixcr assembleContigs

  mem_gb:
    type: object
    properties:
      align:
        type: number
        description: memory (gb) to supply for mixcr align
      refine:
        type: number
        description: memory (gb) to supply for mixcr refineTagsAndSort
      assemble:
        type: number
        description: memory (gb) to supply for mixcr assemble
      export_clones:
        type: number
        description: memory (gb) to supply for mixcr exportClnes
      extend:
        type: number
        description: memory (gb) to supply for mixcr extend

  cutadapt:
    type: object
    properties:
      error_rate:
        type: number
        description: error tolerance used when searching for adapters


required:
  - samplesheet

