$schema: "https://json-schema.org/draft/2020-12/schema"
description: entries for the sample sheet
properties:
  sample_id:
    type: string
    description: sample name/identifier
  10x_chemistry:
    type: string
    default: 5p_v2
    description: 10x chemisry (eg. 5p_v2)
  library_type:
    type: string
    default: cdna
    description: type of library sequenced (eg. cdna, illumina)
  preset:
    type: string
    decription: mixcr preset to use
  read1:
    type: string
    description: path to FASTQ file (read1)

required:
  - sample_id
  - 10x_chemistry
  - library_type
  - read1
