samplesheet: ".test/config/samples.tsv"

conda:
  cutadapt: "../envs/cutadapt.yaml"
  mixcr: "../envs/mixcr.yaml"

threads:
  cutadapt: 16
  align: 16
  extend: 16
  assemble_contigs: 16

mem_gb:
  align: 32
  refine: 16
  assemble: 32
  export_clones: 16
  extend: 16

cutadapt:
  error_rate: 0.1